site_name: QuickForge Studio Documentation
site_url: https://docs.quickforgestudio.com
repo_url: https://github.com/george-shilovsky/quickforge-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
  palette:
    scheme: slate
    primary: blue
    accent: indigo

nav:
  - SaveKitLite:
      - Home: index.md
      - Setup: setup.md
      - Saving & Loading: save-load.md
      - Working with Variables: variables.md
      - UI Integration: ui.md
      - Blueprint Reference: blueprint-reference.md
      - Demo: demo.md
      - Limitations: limitations.md
      - Comparison with UE Save System: comparison.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.copybutton
  - pymdownx.highlight
  - pymdownx.superfences