site_name: QuickForge Studio Documentation
site_url: https://docs.quickforgestudio.com
repo_url: https://github.com/george-shilovsky/quickforge-docs

theme:
  name: material
  logo: images/logo500.png
  favicon: images/logo500.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
  palette:
    scheme: slate
    primary: blue
    accent: indigo

nav:
  - Home: index.md
  - SaveKit Lite:
      - Overview: SaveKitLite/index.md
      - Setup: SaveKitLite/setup.md
      - Save & Load: SaveKitLite/save-load.md
      - UI Integration: SaveKitLite/ui.md
      - Blueprint Reference: SaveKitLite/blueprint-reference.md
      - Limitations: SaveKitLite/limitations.md
      - Variables: SaveKitLite/variables.md
      - Demo: SaveKitLite/demo.md
      - Comparison: SaveKitLite/comparison.md
  - SaveKit Pro:
      - Overview: SaveKitPro/index.md