site_name: QuickForge Studio Documentation
site_url: https://docs.quickforgestudio.com
repo_url: https://github.com/george-shilovsky/quickforge-docs

copyright: Copyright &copy; 2025 QuickForge Studio

theme:
  name: material
  logo: images/logo500.png
  favicon: images/logo500.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
- attr_list

plugins:
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qujzsty4
      name: QuickForge Studio on Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@QuickForgeStudio
      name: QuickForge Studio on Youtube

nav:
  - Home: index.md
  - SaveKit Lite:
    - Getting Started:
      - Overview: SaveKitLite/index.md
      - Quick Start: SaveKitLite/quick-start.md
    - Core Features:
      - Save & Load: SaveKitLite/save-load.md
      - Working with Variables: SaveKitLite/variables.md
      - UI Integration: SaveKitLite/ui.md
    - Developer Reference:
      - Blueprint Reference: SaveKitLite/blueprint-reference.md
      - Limitations: SaveKitLite/limitations.md
      - Comparison: SaveKitLite/comparison.md
    - Examples:
      - Demo: SaveKitLite/demo.md
  - SaveKit Pro:
      - Overview: SaveKitPro/index.md